layout_spectrum: 0.4021246
color:
  saturation: 0.5388634
  lightness: 0.9711233
  brandStrength: 0.9418557
  brandColors:
    - '#0F0D16'
    - '#F3BCAB'
    - '#FFFFFF'
    - '#D79A89'
    - '#B4786D'
  rhythmicContrast: 0.5928679
typography_spectrum: 0.8441939
name: PauravC
